name: Push

on:
  push:
    paths-ignore:
      - '.github/**'
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Run luacheck
        uses: BigWigsMods/actions/luacheck@master
        with:
          args: -q
